### ISSUE TITLE
nodejs自动化测试

### ISSUE THREAD

**Issue by microseyuyu** [microseyuyu/PLCT-Working-issue-nise#16]
nodejs下的test文件夹内的内容进行自动化测试

**Comment by jammyjellyfish** [comment]
test 子文件夹中的: ["benchmark", "embedding", "internet", "abort", "cctest", "es-module", "js-native-api", "addons", "common", "fixtures", "known_issues", "async-hooks", "doctool", "fuzzers", "message"]
完成: ["abort", "async-hooks", "benchmark", "common", "embedding", "es-module", "fixtures", "internet", "known_issues", "message"]

**Comment by jammyjellyfish** [comment]
> test 子文件夹中的: ["benchmark", "embedding", "internet", "abort", "cctest", "es-module", "js-native-api", "addons", "common", "fixtures", "known_issues", "async-hooks", "doctool", "fuzzers", "message"] 完成: ["abort", "async-hooks", "benchmark", "common", "embedding", "es-module", "fixtures", "internet", "known_issues", "message"]


update: test 子文件夹中的 ["node-api", "pummel", "testpy", "wasi", "overlapped-checker", "report", "tick-processor", "wpt", "parallel", "tools", "pseudo-tty", "sequential", "v8-updates"]
