### ISSUE TITLE
DPDK测试

### ISSUE THREAD

**Issue by microseyuyu** [microseyuyu/PLCT-Working-issue-nise#8]
##  测试能不能用 怎么用（可用性） 好用吗（实用性）

- 先使用qemu测
- 成功后使用板子测

[指南](https://doc.dpdk.org/guides/linux_gsg/cross_build_dpdk_for_riscv.html)

**Comment by GICEGreenIce** [comment]
接手：荔枝派测试

**Comment by GICEGreenIce** [comment]
荔枝派及qemu
DPDK测试中止

**Comment by GICEGreenIce** [comment]
测试完成
已提交issue至gitee上的 oe riscv 仓库
